name: the_design_system
description: A new Flutter package project.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  extended_masked_text: ^2.3.1
  flutter:
    sdk: flutter
  
  flutter_launcher_icons: ^0.9.2
  intl: ^0.17.0
  mask_text_input_formatter: ^2.0.0
  validators: ^3.0.0
  auto_size_text_field: ^1.0.1
  weekly_date_picker: ^1.2.0
  flutter_spinkit: ^5.1.0
  date_format: ^2.0.4
  flutter_calendar_carousel: ^2.1.0
  cached_network_image: ^3.1.0
  loading_overlay: ^0.3.0
  table_calendar: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - assets/    
  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf                    
    
  uses-material-design: true
